import 'package:flutter/material.dart';
import 'package:house_construction_pro/screen/role_screen.dart';
import 'package:introduction_screen/introduction_screen.dart';

class IntroPage extends StatefulWidget {
  const IntroPage({super.key});

  @override
  State<IntroPage> createState() => _IntroPageState();
}

class _IntroPageState extends State<IntroPage> {
  void _onIntroEnd(context) {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(
        builder: (context) {
          return RoleSelectionScreen();
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color.fromARGB(255, 166, 177, 240),
      body: Stack(
        children: [
          Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                opacity: 0.1,
                fit: BoxFit.fill,
                image: AssetImage('assets/images/back.jpg'),
              ),
            ),
            child: IntroductionScreen(
              //bodyPadding: EdgeInsets.only(top: 50.0),
              pages: [
                PageViewModel(
                  title: "Welcome to Smart House Planner",
                  body:
                      "An AI-powered platform to help you design your dream home based on plot size and budget.",
                  image: Image.asset("assets/images/intro1.jpg", height: 175.0),
                ),
                // PageViewModel(
                //   title: "AI-Based House Plan Suggestions",
                //   body:
                //       "Enter square feet, land size, and budget — get personalized house plans generated by AI.",
                //   image: Image.asset(
                //   "assets/images/ai_planner.png", height: 175.0),
                // ),
                PageViewModel(
                  title: "Browse & Book Engineers",
                  body:
                      "Explore verified engineers, view their portfolios, and book them directly for your construction project.",
                  image: Image.asset(
                    "assets/images/book eng.jpeg",
                    height: 175.0,
                  ),
                ),
                PageViewModel(
                  title: "Material Suggestions & Future Scope",
                  body:
                      "Get smart material recommendations, price estimates, and hardware store integration.",
                  image: Image.asset(
                    "assets/images/material suggestions.jpg",
                    height: 175.0,
                  ),
                ),
              ],
              showSkipButton: true,
              //showDoneButton: true,
              // back: const Text("Back", style: TextStyle(fontWeight: FontWeight.w600)),
              skip: const Text(
                "Skip",
                style: TextStyle(
                  fontWeight: FontWeight.w600,
                  color: Color.fromARGB(255, 19, 30, 90),
                ),
              ),
              next: const Text(
                "Next",
                style: TextStyle(
                  fontWeight: FontWeight.w600,
                  color: Color.fromARGB(255, 19, 30, 90),
                ),
              ),
              done: const Text(
                "Done",
                style: TextStyle(fontWeight: FontWeight.w600),
              ),
              onDone: () => _onIntroEnd(context),
              dotsDecorator: DotsDecorator(
                size: const Size(10.0, 10.0),
                activeColor: Theme.of(context).colorScheme.secondary,
                color: const Color.fromARGB(255, 12, 22, 82),
                spacing: const EdgeInsets.symmetric(horizontal: 3.0),
                activeShape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(25.0),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
